<?php
/*************************************************************************************************#
# www.rf-cloning.org
#
# Copyright (C) 2009-2014 Steve R. Bond <biologyguy@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as published by
# the Free Software Foundation <http://www.gnu.org/licenses/>
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#*************************************************************************************************/
function sort2d_asc(&$arr, $key)
	{
//we loop through the array and fetch a value that we store in tmp
	for($i = 0; $i < count($arr); $i++)
		{
		$tmp = $arr[$i];
		$pos = false;
		//we check if the key we want to sort by is a string	
		$str = is_numeric($tmp[$key]);
		if(!$str)
			{
			//we loop the array again to compare against the temp value we have
			for($j = $i; $j < count($arr); $j++)
				{
				if(StringManip::is_date($tmp[$key]))
					{
					if(StringManip::compareDates($arr[$j][$key], $tmp[$key], $type = 'asc'))
						{
						$tmp = $arr[$j];
						$pos = $j;
						}
					//we string compare, if the string is "smaller" it will be assigned to the temp value  
					}	
				else if(strcasecmp($arr[$j][$key], $tmp[$key]) < 0)
					{
					$tmp = $arr[$j];
					$pos = $j;
					}
				} 
			}
		else
			{
			for($j = $i; $j < count($arr); $j++)
				{
				if($arr[$j][$key] < $tmp[$key])
					{
					$tmp = $arr[$j];
					$pos = $j;
					}
				}
			}
		if($pos !== false)
			{
			$arr[$pos] = $arr[$i];
			$arr[$i] = $tmp;
			}
		}
	}

$restriction_sites = array("AatII:GACGTC", "AbsI:CCTCGAGG", "Acc65I:GGTACC", "AciI:CCGC", "AclI:AACGTT", "AfeI:AGCGCT", "AflII:CTTAAG", "AgeI:ACCGGT", "AluI:AGCT", "ApaI:GGGCCC", "ApaLI:GTGCAC", "AscI:GGCGCGCC", "AseI:ATTAAT", "AsiSI:GCGATCGC", "AvrII:CCTAGG", "BamHI:GGATCC", "BbvCI:CCTCAGC", "BclI:TGATCA", "BfaI:CTAG", "BfuCI:GATC", "BglII:AGATCT", "BmgBI:CACGTC", "BmtI:GCTAGC", "BseYI:CCCAGC", "BsiWI:CGTACG", "BspDI:ATCGAT", "BspEI:TCCGGA", "BspHI:TCATGA", "BsrBI:CCGCTC", "BsrGI:TGTACA", "BssHII:GCGCGC", "BssSI:CACGAG", "BstBI:TTCGAA", "BstUI:CGCG", "BstZ17I:GTATAC", "ClaI:ATCGAT", "CviAII:CATG", "CviQI:GTAC", "DpnI:GATC", "DpnII:GATC", "DraI:TTTAAA", "EagI:CGGCCG", "Eco53kI:GAGCTC", "EcoRI:GAATTC", "EcoRV:GATATC", "FatI:CATG", "FseI:GGCCGGCC", "FspI:TGCGCA", "HaeIII:GGCC", "HhaI:GCGC", "HinP1I:GCGC", "HindIII:AAGCTT", "HpaI:GTTAAC", "HpaII:CCGG", "HpyCH4IV:ACGT", "HpyCH4V:TGCA", "KasI:GGCGCC", "KpnI:GGTACC", "MauBI:CGCGCGCG", "MboI:GATC", "MfeI:CAATTG", "MluI:ACGCGT", "MreI:CGCCGGCG", "MscI:TGGCCA", "MseI:TTAA", "MspI:CCGG", "NaeI:GCCGGC", "NarI:GGCGCC", "NcoI:CCATGG", "NdeI:CATATG", "NgoMIV:GCCGGC", "NheI:GCTAGC", "NlaIII:CATG", "NotI:GCGGCCGC", "NruI:TCGCGA", "NsiI:ATGCAT", "PacI:TTAATTAA", "PaeR7I:CTCGAG", "PciI:ACATGT", "PhoI:GGCC", "PmeI:GTTTAAAC", "PmlI:CACGTG", "PsiI:TTATAA", "PspOMI:GGGCCC", "PstI:CTGCAG", "PvuI:CGATCG", "PvuII:CAGCTG", "RsaI:GTAC", "SacI:GAGCTC", "SacII:CCGCGG", "SalI:GTCGAC", "Sau3AI:GATC", "SbfI:CCTGCAGG", "ScaI:AGTACT", "SfoI:GGCGCC", "SgrDI:CGTCGACG", "SmaI:CCCGGG", "SnaBI:TACGTA", "SpeI:ACTAGT", "SphI:GCATGC", "SrfI:GCCCGGGC", "SspI:AATATT", "StuI:AGGCCT", "SwaI:ATTTAAAT", "TaqI:TCGA", "TliI:CTCGAG", "Tsp509I:AATT", "TspMI:CCCGGG", "XbaI:TCTAGA", "XhoI:CTCGAG", "XmaI:CCCGGG", "ZraI:GACGTC");

$enzyme_list_array = array();
$sequence = "1	TTC CTC GAG GAA TTC ACT GGATCCCCT CAG GTG CAG GCT GCC TAT CAG AAG GTG GTG GCT GGT GTG 
61	GCC AAT GCC CTG GCT CAC AAA TAC CAC TGA GAT CTT TTT CCC TCT GCC AAA AAT TAT GGG 
121	GAC ATC ATG AAG CCC CTT GAG CAT CTG ACT TCT GGC TAA TAA AGG AAA TTT ATT TTC ATT 
181	GCA ATA GTG TGT TGG AAT TTT TTG TGT CTC TCA CTC GGA AGG ACA TAT GGG AGG GCA AAT 
241	CAT TTA AAA CAT CAG AAT GAG TAT TTG GTT TAG AGT TTG GCA ACA TAT GCC CAT ATG CTG 
301	GCT GCC ATG AAC AAA GGT TGG CTA TAA AGA GGT CAT CAG TAT ATG AAA CAG CCC CCT GCT 
361	GTC CAT TCC TTA TTC CAT AGA AAA GCC TTG ACT TGA GGT TAG ATT TTT TTT ATA TTT TGT 
421	TTT GTG TTA TTT TTT TCT TTA ACA TCC CTA AAA TTT TCC TTA CAT GTT TTA CTA GCC AGA 
481	TTT TTC CTC CTC TCC TGA CTA CTC CCA GTC ATA GCT GTC CCT CTT CTC TTA TGG AGA TCC 
541	CTC GAC CTG CAG CCC AAG CTT GGC GTA ATC ATG GTC ATA GCT GTT TCC TGT GTG AAA TTG 
601	TTA TCC GCT CAC AAT TCC ACA CAA CAT ACG AGC CGG AAG CAT AAA GTG TAA AGC CTG GGT 
661	GCC TAA TGA GTG AGC TAA CTC ACA TTA ATT GCG TTG CGC TCA CTG CCC GCT TTC CAG TCG 
721	GGA AAC CTG TCG TGC CAG CGG ATC CGC ATC TCA ATT AGT CAG CAA CCA TAG TCC CGC CCC 
781	TAA CTC CGC CCA TCC CGC CCC TAA CTC CGC CCA GTT CCG CCC ATT CTC CGC CCC ATG GCT 
841	GAC TAA TTT TTT TTA TTT ATG CAG AGG CCG AGG CCG CCT CGG CCT CTG AGC TAT TCC AGA 
901	AGT AGT GAG GAG GCT TTT TTG GAG GCC TAG GCT TTT GCA AAA AGC TAA CTT GTT TAT TGC 
961	AGC TTA TAA TGG TTA CAA ATA AAG CAA TAG CAT CAC AAA TTT CAC AAA TAA AGC ATT TTT 
1021	TTC ACT GCA TTC TAG TTG TGG TTT GTC CAA ACT CAT CAA TGT ATC TTA TCA TGT CTG GAT 
1081	CCG CTG CAT TAA TGA ATC GGC CAA CGC GCG GGG AGA GGC GGT TTG CGT ATT GGG CGC TCT 
1141	TCC GCT TCC TCG CTC ACT GAC TCG CTG CGC TCG GTC GTT CGG CTG CGG CGA GCG GTA TCA 
1201	GCT CAC TCA AAG GCG GTA ATA CGG TTA TCC ACA GAA TCA GGG ATA ACG CAG GAA AGA ACA 
1261	TGT GAG CAA AAG GCC AGC AAA AGG CCA GGA ACC GTA AAA AGG CCG CGT TGC TGG CGT TTT 
1321	TCC ATA GGC TCC GCC CCC CTG ACG AGC ATC ACA AAA ATC GAC GCT CAA GTC AGA GGT GGC 
1381	GAA ACC CGA CAG GAC TAT AAA GAT ACC AGG CGT TTC CCC CTG GAA GCT CCC TCG TGC GCT 
1441	CTC CTG TTC CGA CCC TGC CGC TTA CCG GAT ACC TGT CCG CCT TTC TCC CTT CGG GAA GCG 
1501	TGG CGC TTT CTC ATA GCT CAC GCT GTA GGT ATC TCA GTT CGG TGT AGG TCG TTC GCT CCA 
1561	AGC TGG GCT GTG TGC ACG AAC CCC CCG TTC AGC CCG ACC GCT GCG CCT TAT CCG GTA ACT 
1621	ATC GTC TTG AGT CCA ACC CGG TAA GAC ACG ACT TAT CGC CAC TGG CAG CAG CCA CTG GTA 
1681	ACA GGA TTA GCA GAG CGA GGT ATG TAG GCG GTG CTA CAG AGT TCT TGA AGT GGT GGC CTA 
1741	ACT ACG GCT ACA CTA GAA GAA CAG TAT TTG GTA TCT GCG CTC TGC TGA AGC CAG TTA CCT 
1801	TCG GAA AAA GAG TTG GTA GCT CTT GAT CCG GCA AAC AAA CCA CCG CTG GTA GCG GTG GTT 
1861	TTT TTG TTT GCA AGC AGC AGA TTA CGC GCA GAA AAA AAG GAT CTC AAG AAG ATC CTT TGA 
1921	TCT TTT CTA CGG GGT CTG ACG CTC AGT GGA ACG AAA ACT CAC GTT AAG GGA TTT TGG TCA 
1981	TGA GAT TAT CAA AAA GGA TCT TCA CCT AGA TCC TTT TAA ATT AAA AAT GAA GTT TTA AAT 
2041	CAA TCT AAA GTA TAT ATG AGT AAA CTT GGT CTG ACA GTT ACC AAT GCT TAA TCA GTG AGG 
2101	CAC CTA TCT CAG CGA TCT GTC TAT TTC GTT CAT CCA TAG TTG CCT GAC TCC CCG TCG TGT 
2161	AGA TAA CTA CGA TAC GGG AGG GCT TAC CAT CTG GCC CCA GTG CTG CAA TGA TAC CGC GAG 
2221	ACC CAC GCT CAC CGG CTC CAG ATT TAT CAG CAA TAA ACC AGC CAG CCG GAA GGG CCG AGC 
2281	GCA GAA GTG GTC CTG CAA CTT TAT CCG CCT CCA TCC AGT CTA TTA ATT GTT GCC GGG AAG 
2341	CTA GAG TAA GTA GTT CGC CAG TTA ATA GTT TGC GCA ACG TTG TTG CCA TTG CTA CAG GCA 
2401	TCG TGG TGT CAC GCT CGT CGT TTG GTA TGG CTT CAT TCA GCT CCG GTT CCC AAC GAT CAA 
2461	GGC GAG TTA CAT GAT CCC CCA TGT TGT GCA AAA AAG CGG TTA GCT CCT TCG GTC CTC CGA 
2521	TCG TTG TCA GAA GTA AGT TGG CCG CAG TGT TAT CAC TCA TGG TTA TGG CAG CAC TGC ATA 
2581	ATT CTC TTA CTG TCA TGC CAT CCG TAA GAT GCT TTT CTG TGA CTG GTG AGT ACT CAA CCA 
2641	AGT CAT TCT GAG AAT AGT GTA TGC GGC GAC CGA GTT GCT CTT GCC CGG CGT CAA TAC GGG 
2701	ATA ATA CCG CGC CAC ATA GCA GAA CTT TAA AAG TGC TCA TCA TTG GAA AAC GTT CTT CGG 
2761	GGC GAA AAC TCT CAA GGA TCT TAC CGC TGT TGA GAT CCA GTT CGA TGT AAC CCA CTC GTG 
2821	CAC CCA ACT GAT CTT CAG CAT CTT TTA CTT TCA CCA GCG TTT CTG GGT GAG CAA AAA CAG 
2881	GAA GGC AAA ATG CCG CAA AAA AGG GAA TAA GGG CGA CAC GGA AAT GTT GAA TAC TCA TAC 
2941	TCT TCC TTT TTC AAT ATT ATT GAA GCA TTT ATC AGG GTT ATT GTC TCA TGA GCG GAT ACA 
3001	TAT TTG AAT GTA TTT AGA AAA ATA AAC AAA TAG GGG TTC CGC GCA CAT TTC CCC GAA AAG 
3061	TGC CAC CTG GGT CGA CAT TGA TTA TTG ACT AGT TAT TAA TAG TAA TCA ATT ACG GGG TCA 
3121	TTA GTT CAT AGC CCA TAT ATG GAG TTC CGC GTT ACA TAA CTT ACG GTA AAT GGC CCG CCT 
3181	GGC TGA CCG CCC AAC GAC CCC CGC CCA TTG ACG TCA ATA ATG ACG TAT GTT CCC ATA GTA 
3241	ACG CCA ATA GGG ACT TTC CAT TGA CGT CAA TGG GTG GAG TAT TTA CGG TAA ACT GCC CAC 
3301	TTG GCA GTA CAT CAA GTG TAT CAT ATG CCA AGT ACG CCC CCT ATT GAC GTC AAT GAC GGT 
3361	AAA TGG CCC GCC TGG CAT TAT GCC CAG TAC ATG ACC TTA TGG GAC TTT CCT ACT TGG CAG 
3421	TAC ATC TAC GTA TTA GTC ATC GCT ATT ACC ATG GTC GAG GTG AGC CCC ACG TTC TGC TTC 
3481	ACT CTC CCC ATC TCC CCC CCC TCC CCA CCC CCA ATT TTG TAT TTA TTT ATT TTT TAA TTA 
3541	TTT TGT GCA GCG ATG GGG GCG GGG GGG GGG GGG GGG CCC CCC CCA GGC GGG GCG GGG CGG 
3601	GGC GAG GGG CGG GGC GGG GCG AGG CGG AAA GGT GCG GCG GCA GCC AAT CAG AGC GGC GCG 
3661	CTC CGA AAG TTT CCT TTT ATG GCG AGG CGG CGG CGG CGG CGG CCC TAT AAA AAG CGA AGC 
3721	GCG CGG CGG GCG GGA GTC GTT GCG CGC TGC CTT CCC CCC GTG CCC CGC TCC GCC GCC GCC 
3781	TCG CGC CGC CCG CCC CGG CTC TGA CTG ACC GCG TTA CTC CCA CAG GTG AGC GGG CGG GAC 
3841	GGC CCT TCT CCT CCG GGC TGT AAT TAG CGC TTG GTT TAA TGA CGG CTT GTT TCT TTT CTG 
3901	TGG CTG CGT GAA AGC CTT GAG GGG CTC CGG GAG GGC CCT TTG TGC GGG GGG AGC GGC TCG 
3961	GGG GGT GCG TGC GTG TGT GTG TGC GTG GGG AGC GCC GCG TGC GGC TCC GCG CTG CCC GGC 
4021	GGC TGT GAG CGC TGC GGG CGC GGC GCG GGG CTT TGT GCG CTC CGC AGT GTG CGC GAG GGG 
4081	AGC GCG GCC GGG GGC GGT GCC CCG CGG TGC GGG GGG GGC TGC GAG GGG AAC AAA GGC TGC 
4141	GTG CGG GGT GTG TGC GTG GGG GGG TGA GCA GGG GGT GTG GGC GCG TCG GTC GGG CTG CAA 
4201	CCC CCC CTG CAC CCC CCT CCC CGA GTT GCT GAG CAC GGC CCG GCT TCG GGT GCG GGG CTC 
4261	CGT ACG GGG CGT GGC GCG GGG CTC GCC GTG CCG GGC GGG GGG TGG CGG CAG GTG GGG GTG 
4321	CCG GGC GGG GCG GGG CCG CCT CGG GCC GGG GAG GGC TCG GGG GAA GGG GCG CGG CGG CCC 
4381	CCG GAG CGC CGG CGG CTG TCG AGG CGC GGC GAG CCG CAG CCA TTG CCT TTT ATG GTA ATC 
4441	GTG CGA GAG GGC GCA GGG ACT TCC TTT GTC CCA AAT CTG TGC GGA GCC GAA ATC TGG GAG 
4501	GCG CCG CCG CAC CCC CTC TAG CGG GCG CGG GGC GAA GCG GTG CGG CGC CGG CAG GAA GGA 
4561	AAT GGG CGG GGA GGG CCT TCG TGC GTC GCC GCG CCG CCG TCC CCT TCT CCC TCT CCA GCC 
4621	TCG GGG CTG TCC GCG GGG GGA CGG CTG CCT TCG GGG GGG ACG GGG CAG GGC GGG GTT CGG 
4681	CTT CTG GCG TGT GAC CGG CGG CTC TAG AGC CTC TGC TAA CCA TGT TCA TGC CTT CTT CTT 
4741	TTT CCT ACA GCT CCT GGG CAA CGT GCT GGT TAT TGT GCT GTC TCA TCA TTT TGG CAA AGA 
4801	A ";

$sequence = preg_replace('/[^ATCG]/i','',$sequence);
foreach($restriction_sites as $row)
	{
	$cur_enzyme = explode(":",$row);
	//$sequence = $_POST['sequence'];
	$offset=0;
	while ($position = strpos($sequence,$cur_enzyme[1],$offset))
		{
		$enzyme = array($cur_enzyme[0], $position);
		array_push($enzyme_list_array,$enzyme);
		$offset = $position + strlen($cur_enzyme[0]);	
		}
	}

sort2d_asc($enzyme_list_array,1);

foreach($enzyme_list_array as $row)
	{
	echo $row[0]." ".$row[1].":";	
	}
?>